
[role='navig']
****

.General
* link:index.html[Main page]
* link:bcftools.html[Manual page]
* link:install.html[Installation]

.Calling
* link:cnv-calling.html[CNV calling]
* link:consensus-sequence.html[Consensus calling]
* link:variant-calling.html[Variant calling]

.Manipulating VCF/BCF
* link:filtering.html[Filtering]

.Tips and Tricks
* link:query.html[Extracting information]
* link:plugins.html[Plugins]

****

// Disable last updated text.
:last-update-label!:


++++
<div id="main">
++++

